apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: bro-frontend
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{image}}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  port: 3000
  tokenx:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
      autoLogin: true
      level: Level4
      autoLoginIgnorePaths:
        - /syk/kartleggingssporsmal/api/internal/isAlive
        - /syk/kartleggingssporsmal/api/internal/isReady
  liveness:
    path: /syk/kartleggingssporsmal/api/internal/isAlive
    initialDelay: 20
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /syk/kartleggingssporsmal/api/internal/isReady
    initialDelay: 20
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: actuator/metrics
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  ingresses:
    - 'https://www.ekstern.dev.nav.no/syk/kartleggingssporsmal'
  env:
    - name: MEROPPFOLGING_BACKEND_URL
      value: http://meroppfolging-backend
    - name: FLEXJAR_BACKEND_HOST
      value: http://flexjar-backend.flex
    - name: FLEXJAR_BACKEND_CLIENT_ID
      value: prod-gcp:flex:flexjar-backend
  accessPolicy:
    outbound:
      rules:
        - application: nav-dekoratoren
          namespace: personbruker
        - application: meroppfolging-backend
        - application: flexjar-backend
          namespace: flex
